project:
  type: book

book:
  title: "Variables Aleatorias Discretas"
  author: "Licenciatura en Ciencias Agrogenómicas"
  chapters:
    - index.qmd
    - TCL.qmd
    - uniforme_discreta.qmd
    - bernoulli_binomial.qmd
    - geometrica.qmd
    - binomial_negativa.qmd
    - hipergeometrica.qmd
    - poisson.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 250px
      gutter-width: 1.5rem
    code-fold: true
    fig-width: 8
    fig-height: 6
    fig-align: "center"




